### ISSUE TITLE
How I can check return value from main function?

### ISSUE THREAD

**Issue by playXE** [softdevteam/lang_tester#4]
Let's say we have this code in some file:
```go
pub func main() i32 {
     var variable = awesome_function();
     return variable;
}
```
How I can check this return using lang tester?

**Comment by ltratt** [comment]
As things stand at this very moment, your best bet is something like:

```rust
// Command:
//   stdout: 5

fn main() {
    println!("{}", awesome_func());
}
```

That said, we deliberately designed the `status` field so that it can be extended to allow integer checks later (see https://github.com/softdevteam/lang_tester/pull/1#discussion_r283297733). It's currently unimplemented though, because the above idiom seems good enough for most cases. I'm happy to be convinced that I'm wrong.

**Comment by playXE** [comment]
Thanks for the answer! For now, I use `--jit` option in my compiler to properly test main return since with jit option my compiler prints exit value to stdout. I think it's necessary to add support for checking program output since if in code called `exit(-1)` function we get -1 as an output of the program.

**Comment by ltratt** [comment]
I've added support for this in https://github.com/softdevteam/lang_tester/pull/5. Feel free to try it and comment on it on the PR!

**Comment by playXE** [comment]
Just tried to use it in my projects, everything works fine!
